CC-36490: Add read access verification for schema history topic during startup (#208)
What?
------
Addressing: https://confluentinc.atlassian.net/browse/CC-36490

Approach:
https://confluentinc.atlassian.net/wiki/spaces/~804931684/pages/4786389027/DBZ+V2+Schema-History+Based+Connectors+ACL+issues

Testing
-------
Tested the changes on the Devel canary.

Before this change:
- If the configured service account did not have the CREATE ACL for the
schema-history topic, the connector failed at startup.
- If it had CREATE but not WRITE ACL, the connector still failed at
startup.
- If it had CREATE and WRITE ACLs but lacked READ ACL on the
schema-history topic or its consumer group, the connector failed after a
restart.

After this change:
- If the configured service account lacks any of the required ACLs
(CREATE, WRITE, or READ), the connector now fails immediately at
startup.

Exception stacktrace for missing READ ACL on schema-history topic:
```
io.debezium.DebeziumException: Failed to read from schema history topic. Ensure that the connector has the necessary permissions to read from the schema-history topic.
  at io.debezium.connector.v2.common.BaseSourceTask.validateSchemaHistory(BaseSourceTask.java:101)
  at io.debezium.connector.v2.mysql.MySqlConnectorTask.start(MySqlConnectorTask.java:144)
  at io.debezium.connector.v2.common.BaseSourceTask.start(BaseSourceTask.java:257)
  at org.apache.kafka.connect.runtime.AbstractWorkerSourceTask.initializeAndStart(AbstractWorkerSourceTask.java:299)
  at org.apache.kafka.connect.runtime.WorkerTask.doStart(WorkerTask.java:208)
  at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:271)
  at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:328)
  at org.apache.kafka.connect.runtime.AbstractWorkerSourceTask.run(AbstractWorkerSourceTask.java:88)
  at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$7(Plugins.java:341)
  at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
  at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
  at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: io.debezium.relational.history.SchemaHistoryException: Failed to verify read access to database schema history topic 'dbhistory.test123.lcc-devczoqxo3'. This could be due to insufficient permissions or incorrect configuration.
  at io.debezium.storage.kafka.history.KafkaSchemaHistory.verifyReadAccess(KafkaSchemaHistory.java:655)
  at io.debezium.connector.v2.common.BaseSourceTask.validateSchemaHistory(BaseSourceTask.java:98)
  ... 13 more
Caused by: org.apache.kafka.common.errors.TopicAuthorizationException: Not authorized to access topics: [dbhistory.test123.lcc-devczoqxo3]
```

Exception stacktrace for missing READ ACL on consumer-group of
schema-history topic:
```
io.debezium.DebeziumException: Failed to read from schema history topic. Ensure that the connector has the necessary permissions to read from the schema-history topic.
  at io.debezium.connector.v2.common.BaseSourceTask.validateSchemaHistory(BaseSourceTask.java:101)
  at io.debezium.connector.v2.mysql.MySqlConnectorTask.start(MySqlConnectorTask.java:144)
  at io.debezium.connector.v2.common.BaseSourceTask.start(BaseSourceTask.java:257)
  at org.apache.kafka.connect.runtime.AbstractWorkerSourceTask.initializeAndStart(AbstractWorkerSourceTask.java:299)
  at org.apache.kafka.connect.runtime.WorkerTask.doStart(WorkerTask.java:208)
  at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:271)
  at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:328)
  at org.apache.kafka.connect.runtime.AbstractWorkerSourceTask.run(AbstractWorkerSourceTask.java:88)
  at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$7(Plugins.java:341)
  at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
  at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
  at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: io.debezium.relational.history.SchemaHistoryException: Failed to verify read access to database schema history topic 'dbhistory.test123.lcc-devczoqxo3'. This could be due to insufficient permissions or incorrect configuration.
  at io.debezium.storage.kafka.history.KafkaSchemaHistory.verifyReadAccess(KafkaSchemaHistory.java:655)
  at io.debezium.connector.v2.common.BaseSourceTask.validateSchemaHistory(BaseSourceTask.java:98)
  ... 13 more
Caused by: org.apache.kafka.common.errors.GroupAuthorizationException: Not authorized to access group: test123-schemahistory
```

Cherry-Picked-From: 5cee5df339
Cherry-Picked-By: Bhagyashree <bhagyashree@confluent.io>
Cherry-Picked-At: Fri Mar 13 08:29:55 2026 +0000