CC-37107: Add # to the accepted chars regex (#241)
For Oracle Connectors the table includes a `#` character. With the
current regex it errors out with # in the include list with this
exception:

```
	org.apache.kafka.connect.errors.ConnectException: io.debezium.DebeziumException: Invalid include list format. Please specify a list of rules in the format of "source:<tablename>:<fieldnames>", "topic:<topicname>:<fieldnames>", "<matchname>:<fieldnames>"
	at org.apache.kafka.connect.runtime.ConnectorConfig.transformationStages(ConnectorConfig.java:346)
	at org.apache.kafka.connect.runtime.Worker$SourceTaskBuilder.doBuild(Worker.java:2362)
	at org.apache.kafka.connect.runtime.Worker$TaskBuilder.build(Worker.java:2179)
	at org.apache.kafka.connect.runtime.Worker.buildWorkerTask(Worker.java:800)
	at org.apache.kafka.connect.runtime.Worker.startTask(Worker.java:885)
	at org.apache.kafka.connect.runtime.Worker.startSourceTask(Worker.java:695)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startTask(DistributedHerder.java:2264)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.lambda$restartTask$30(DistributedHerder.java:1574)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.runRequest(DistributedHerder.java:2607)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.tick(DistributedHerder.java:513)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:394)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: io.debezium.DebeziumException: Invalid include list format. Please specify a list of rules in the format of "source:<tablename>:<fieldnames>", "topic:<topicname>:<fieldnames>", "<matchname>:<fieldnames>"
	at io.debezium.transforms.TimezoneConverter.validateConfiguration(TimezoneConverter.java:222)
	at io.debezium.transforms.TimezoneConverter.configure(TimezoneConverter.java:170)
	at org.apache.kafka.connect.runtime.ConnectorConfig.transformationStages(ConnectorConfig.java:326)
	... 15 more
```


Adding `#` to the accepted chars pattern.